//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanMyTripDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hotel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hotel()
        {
            this.RoomDetails = new HashSet<RoomDetail>();
        }
    
        public int HoteId { get; set; }
        public string City { get; set; }
        public string HotelName { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public Nullable<int> AvrRoomRent { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Email { get; set; }
    
    //    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomDetail> RoomDetails { get; set; }
    }
}
